# services:
#   postgres:
#     image: pgvector/pgvector:pg16
#     container_name: fibochat-db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: FiboChatPlatform
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

version: "3.9"

services:
  gateway:
    build:
      context: ../src
      dockerfile: gateway/Gateway.Api/Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - authentication
      - course-api

  authentication:
    build:
      context: ../src
      dockerfile: services/Authentication/Authentication.API/Dockerfile
    container_name: authentication
    ports:
      - "5001:5001"

  course-api:
    build:
      context: ../src
      dockerfile: services/Course/Course.Api/Dockerfile
    container_name: course-api
    ports:
      - "5002:5002"

  # redis:
  #   image: redis:7.2
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  redis_data:

