services:
  # PostgreSQL cho Authentication service
  postgres-auth:
    image: pgvector/pgvector:pg16
    container_name: fibochat-db-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fibo_chat-auth
    ports:
      - "5432:5432"
    volumes:
      - pgauth:/var/lib/postgresql/data
    networks:
      - fibochat-network

  # PostgreSQL cho Course service
  postgres-course:
    image: pgvector/pgvector:pg16
    container_name: fibochat-db-course
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fibo_chat-course
    ports:
      - "5433:5432" # Port khác để tránh conflict
    volumes:
      - pgcourse:/var/lib/postgresql/data
    networks:
      - fibochat-network

  gateway:
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    container_name: fibochat-gateway
    restart: always
    ports:
      - "7007:8081" # HTTPS
      - "5045:8080" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - auth-service
      - course-service
    networks:
      - fibochat-network

  auth-service:
    build:
      context: .
      dockerfile: services/Authentication/API/Dockerfile
    container_name: fibo_chat-auth
    restart: always
    ports:
      - "5001:8081" # HTTPS
      - "5000:8080" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DbConnection=Host=postgres-auth;Database=fibo_chat-auth;Username=postgres;Password=123456
    depends_on:
      - postgres-auth
    networks:
      - fibochat-network

  course-service:
    build:
      context: .
      dockerfile: services/Course/Course.Api/Dockerfile
    container_name: fibo_chat-course
    restart: always
    ports:
      - "7212:8081" # HTTPS
      - "5224:8080" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DBConnection=Host=postgres-course;Database=fibo_chat-course;Username=postgres;Password=123456
    depends_on:
      - postgres-course
    networks:
      - fibochat-network

volumes:
  pgauth:
  pgcourse:

networks:
  fibochat-network:
    driver: bridge
