version: "3.9"

services:
  postgres-auth:
    image: postgres:16
    container_name: fibochat-auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fibo_chat-auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - fibo-net

  postgres-course:
    image: postgres:16
    container_name: fibochat-course-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fibo_chat-course
    ports:
      - "5434:5432"
    volumes:
      - postgres_course_data:/var/lib/postgresql/data
    networks:
      - fibo-net

  authentication:
    build:
      context: .
      dockerfile: services/Authentication/Authentication.API/Dockerfile
    container_name: fibochat-auth
    restart: always
    depends_on:
      - postgres-auth
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__DbConnection: "Host=postgres-auth;Port=5432;Database=fibo_chat_auth;Username=postgres;Password=123456"
      Authentication__Issuer: "http://fibochat-auth:5001"
      Authentication__Audience: "http://fibochat-auth:5001"
    ports:
      - "5001:5001"
    networks:
      - fibo-net

  course-api:
    build:
      context: .
      dockerfile: services/Course/Course.Api/Dockerfile
    container_name: fibochat-course
    restart: always
    depends_on:
      - postgres-course
      - authentication
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__CourseDb: "Host=postgres-course;Port=5432;Database=fibo_chat_course;Username=postgres;Password=123456;SearchPath=course"
      Services__AuthBaseUrl: "http://fibochat-auth:5001"
    ports:
      - "5002:5002"
    networks:
      - fibo-net

  gateway:
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    container_name: fibochat-gateway
    restart: always
    depends_on:
      - authentication
      - course-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      Services__AuthBaseUrl: "http://fibochat-auth:5001"
      Services__CourseBaseUrl: "http://fibochat-course:5002"
    ports:
      - "5045:8080"
    networks:
      - fibo-net

  redis:
    image: redis:7.2
    container_name: fibochat-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - fibo-net

networks:
  fibo-net:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_course_data:
  redis_data:
